<?php

declare(strict_types=1);

namespace Tests\Battle\Unit\Offense;

use Battle\Unit\Defense\Defense;
use Battle\Unit\Defense\DefenseInterface;
use Battle\Unit\Offense\OffenseException;
use Battle\Unit\Offense\OffenseFactory;
use Battle\Unit\Offense\OffenseInterface;
use Exception;
use Tests\AbstractUnitTest;

class OffenseFactoryTest extends AbstractUnitTest
{
    /**
     * Тест на успешное создание Offense
     *
     * @dataProvider successDataProvider
     * @param array $data
     * @throws Exception
     */
    public function testOffenseFactoryCreateSuccess(array $data): void
    {
        $offense = $this->getFactory()->create($data, $this->container);

        // Так как сопротивления нулевые - итоговый урон будет суммой всех типов урона
        self::assertEquals(
            $data['physical_damage'] + $data['fire_damage'] + $data['water_damage'] + $data['air_damage'] + $data['earth_damage'] + $data['life_damage'] + $data['death_damage'],
            $offense->getDamage($this->getDefense())
        );

        self::assertEquals($data['damage_type'], $offense->getDamageType());
        self::assertEquals($data['weapon_type'], $offense->getWeaponType()->getId());
        self::assertEquals($data['physical_damage'], $offense->getPhysicalDamage());
        self::assertEquals($data['fire_damage'], $offense->getFireDamage());
        self::assertEquals($data['water_damage'], $offense->getWaterDamage());
        self::assertEquals($data['air_damage'], $offense->getAirDamage());
        self::assertEquals($data['earth_damage'], $offense->getEarthDamage());
        self::assertEquals($data['life_damage'], $offense->getLifeDamage());
        self::assertEquals($data['death_damage'], $offense->getDeathDamage());
        self::assertEquals(
            $data['physical_damage'] + $data['fire_damage'] + $data['water_damage'] + $data['air_damage'] + $data['earth_damage'] + $data['life_damage'] + $data['death_damage'],
            $offense->getDamageSum()
        );

        self::assertEquals($data['attack_speed'], $offense->getAttackSpeed());
        self::assertEquals($data['cast_speed'], $offense->getCastSpeed());
        self::assertEquals($data['accuracy'], $offense->getAccuracy());
        self::assertEquals($data['magic_accuracy'], $offense->getMagicAccuracy());
        self::assertEquals($data['block_ignoring'], $offense->getBlockIgnoring());

        self::assertEquals($data['critical_chance'], $offense->getCriticalChance());
        self::assertEquals($data['critical_multiplier'], $offense->getCriticalMultiplier());
        self::assertEquals($data['damage_multiplier'], $offense->getDamageMultiplier());
        self::assertEquals($data['vampirism'], $offense->getVampirism());
        self::assertEquals($data['magic_vampirism'], $offense->getMagicVampirism());
    }

    /**
     * Тест на некорректные данные для создания Offense
     *
     * @dataProvider failDataProvider
     * @param array $data
     * @param string $error
     * @throws Exception
     */
    public function testOffenseFactoryCreateFail(array $data, string $error): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage($error);
        $this->getFactory()->create($data, $this->container);
    }

    /**
     * @return array
     */
    public function successDataProvider(): array
    {
        return [
            [
                // Скорость атаки и создания заклинаний int
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 3,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 3,
                ],
            ],
            [
                // Скорость атаки и создания заклинаний float
                [
                    'damage_type'         => 2,
                    'weapon_type'         => 17,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1.3,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 100,
                    'critical_multiplier' => 150,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 100,
                    'magic_vampirism'     => 0,
                ],
            ],
            [
                // урон со всех стихий
                [
                    'damage_type'         => 2,
                    'weapon_type'         => 17,
                    'physical_damage'     => 110,
                    'fire_damage'         => 120,
                    'water_damage'        => 130,
                    'air_damage'          => 140,
                    'earth_damage'        => 150,
                    'life_damage'         => 160,
                    'death_damage'        => 170,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 100,
                    'critical_multiplier' => 150,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 100,
                    'magic_vampirism'     => 0,
                ],
            ],
        ];
    }

    /**
     * @return array
     */
    public function failDataProvider(): array
    {
        return [

            // damage_type
            [
                // Отсутствует damage_type
                [
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_DAMAGE_TYPE,
            ],
            [
                // damage_type некорректного типа
                [
                    'damage_type'         => '1',
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_DAMAGE_TYPE,
            ],
            [
                // damage_type выходит за пределы допустимых значений (1 или 2)
                [
                    'damage_type'         => 3,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_DAMAGE_TYPE_VALUE,
            ],

            // physical_damage
            [
                // Отсутствует physical_damage
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_PHYSICAL_DAMAGE,
            ],
            [
                // physical_damage некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10.5,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_PHYSICAL_DAMAGE,
            ],
            [
                // physical_damage меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => OffenseInterface::MIN_DAMAGE - 1,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_PHYSICAL_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],
            [
                // physical_damage больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => OffenseInterface::MAX_DAMAGE + 1,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_PHYSICAL_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],

            // fire_damage
            [
                // Отсутствует fire_damage
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_FIRE_DAMAGE,
            ],
            [
                // fire_damage некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => [0],
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_FIRE_DAMAGE,
            ],
            [
                // fire_damage меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => OffenseInterface::MIN_DAMAGE - 1,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_FIRE_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],
            [
                // fire_damage больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => OffenseInterface::MAX_DAMAGE + 1,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_FIRE_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],

            // water_damage
            [
                // Отсутствует water_damage
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_WATER_DAMAGE,
            ],
            [
                // water_damage некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => '0',
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_WATER_DAMAGE,
            ],
            [
                // water_damage меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => OffenseInterface::MIN_DAMAGE - 1,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_WATER_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],
            [
                // water_damage больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => OffenseInterface::MAX_DAMAGE + 1,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_WATER_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],

            // air_damage
            [
                // Отсутствует air_damage
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_AIR_DAMAGE,
            ],
            [
                // air_damage некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0.0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_AIR_DAMAGE,
            ],
            [
                // air_damage меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => OffenseInterface::MIN_DAMAGE - 1,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_AIR_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],
            [
                // air_damage больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => OffenseInterface::MAX_DAMAGE + 1,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_AIR_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],

            // earth_damage
            [
                // Отсутствует earth_damage
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_EARTH_DAMAGE,
            ],
            [
                // earth_damage некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => true,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_EARTH_DAMAGE,
            ],
            [
                // earth_damage меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => OffenseInterface::MIN_DAMAGE - 1,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_EARTH_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],
            [
                // earth_damage больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => OffenseInterface::MAX_DAMAGE + 1,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_EARTH_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],

            // life_damage
            [
                // Отсутствует life_damage
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_LIFE_DAMAGE,
            ],
            [
                // life_damage некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => null,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_LIFE_DAMAGE,
            ],
            [
                // life_damage меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => OffenseInterface::MIN_DAMAGE - 1,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_LIFE_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],
            [
                // life_damage больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => OffenseInterface::MAX_DAMAGE + 1,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_LIFE_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],

            // death_damage
            [
                // Отсутствует death_damage
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_DEATH_DAMAGE,
            ],
            [
                // death_damage некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => false,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_DEATH_DAMAGE,
            ],
            [
                // death_damage меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => OffenseInterface::MIN_DAMAGE - 1,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_DEATH_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],
            [
                // death_damage больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => OffenseInterface::MAX_DAMAGE + 1,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_DEATH_DAMAGE_VALUE . OffenseInterface::MIN_DAMAGE . '-' . OffenseInterface::MAX_DAMAGE,
            ],

            // attack_speed
            [
                // Отсутствует attack_speed
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_ATTACK_SPEED,
            ],
            [
                // attack_speed некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => true,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_ATTACK_SPEED,
            ],
            [
                // attack_speed меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => OffenseInterface::MIN_ATTACK_SPEED - 0.1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_ATTACK_SPEED_VALUE . OffenseInterface::MIN_ATTACK_SPEED . '-' . OffenseInterface::MAX_ATTACK_SPEED,
            ],
            [
                // attack_speed больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => OffenseInterface::MAX_ATTACK_SPEED + 0.1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_ATTACK_SPEED_VALUE . OffenseInterface::MIN_ATTACK_SPEED . '-' . OffenseInterface::MAX_ATTACK_SPEED,
            ],

            // cast_speed
            [
                // Отсутствует cast_speed
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CAST_SPEED,
            ],
            [
                // cast_speed некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => null,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CAST_SPEED,
            ],
            [
                // cast_speed меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => OffenseInterface::MIN_CAST_SPEED - 0.1,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CAST_SPEED_VALUE . OffenseInterface::MIN_CAST_SPEED . '-' . OffenseInterface::MAX_CAST_SPEED,
            ],
            [
                // cast_speed больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => OffenseInterface::MAX_CAST_SPEED + 0.1,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CAST_SPEED_VALUE . OffenseInterface::MIN_CAST_SPEED . '-' . OffenseInterface::MAX_CAST_SPEED,
            ],

            // accuracy
            [
                // Отсутствует accuracy
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1.3,
                    'cast_speed'          => 1.7,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_ACCURACY,
            ],
            [
                // accuracy некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1.3,
                    'cast_speed'          => 1.7,
                    'accuracy'            => [200],
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_ACCURACY,
            ],
            [
                // accuracy меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1.3,
                    'cast_speed'          => 1.7,
                    'accuracy'            => OffenseInterface::MIN_ACCURACY - 1,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_ACCURACY_VALUE . OffenseInterface::MIN_ACCURACY . '-' . OffenseInterface::MAX_ACCURACY,
            ],
            [
                // accuracy больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1.3,
                    'cast_speed'          => 1.7,
                    'accuracy'            => OffenseInterface::MAX_ACCURACY + 1,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_ACCURACY_VALUE . OffenseInterface::MIN_ACCURACY . '-' . OffenseInterface::MAX_ACCURACY,
            ],

            // magic_accuracy
            [
                // Отсутствует magic_accuracy
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_MAGIC_ACCURACY,
            ],
            [
                // magic_accuracy некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => '100',
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_MAGIC_ACCURACY,
            ],
            [
                // magic_accuracy меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => OffenseInterface::MIN_MAGIC_ACCURACY - 1,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_MAGIC_ACCURACY_VALUE . OffenseInterface::MIN_MAGIC_ACCURACY . '-' . OffenseInterface::MAX_MAGIC_ACCURACY,
            ],
            [
                // magic_accuracy больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => OffenseInterface::MAX_MAGIC_ACCURACY + 1,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_MAGIC_ACCURACY_VALUE . OffenseInterface::MIN_MAGIC_ACCURACY . '-' . OffenseInterface::MAX_MAGIC_ACCURACY,
            ],

            // block_ignore
            [
                // Отсутствует block_ignore
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1.3,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_BLOCK_IGNORING,
            ],
            [
                // block_ignore некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1.3,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0.0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_BLOCK_IGNORING,
            ],
            [
                // block_ignore меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1.3,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => OffenseInterface::MIN_BLOCK_IGNORING - 1,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_BLOCK_IGNORING_VALUE . OffenseInterface::MIN_BLOCK_IGNORING . '-' . OffenseInterface::MAX_BLOCK_IGNORING,
            ],
            [
                // block_ignore больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1.3,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => OffenseInterface::MAX_BLOCK_IGNORING + 1,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_BLOCK_IGNORING_VALUE . OffenseInterface::MIN_BLOCK_IGNORING . '-' . OffenseInterface::MAX_BLOCK_IGNORING,
            ],

            // critical_chance
            [
                // Отсутствует critical_chance
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CRITICAL_CHANCE,
            ],
            [
                // critical_chance некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => true,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CRITICAL_CHANCE,
            ],
            [
                // critical_chance меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => OffenseInterface::MIN_CRITICAL_CHANCE - 1,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CRITICAL_CHANCE_VALUE . OffenseInterface::MIN_CRITICAL_CHANCE . '-' . OffenseInterface::MAX_CRITICAL_CHANCE,
            ],
            [
                // critical_chance больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => OffenseInterface::MAX_CRITICAL_CHANCE + 1,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CRITICAL_CHANCE_VALUE . OffenseInterface::MIN_CRITICAL_CHANCE . '-' . OffenseInterface::MAX_CRITICAL_CHANCE,
            ],

            // critical_multiplier
            [
                // Отсутствует critical_multiplier
                [
                    'damage_type'       => 1,
                    'weapon_type'       => 1,
                    'physical_damage'   => 10,
                    'fire_damage'       => 0,
                    'water_damage'      => 0,
                    'air_damage'        => 0,
                    'earth_damage'      => 0,
                    'life_damage'       => 0,
                    'death_damage'      => 0,
                    'attack_speed'      => 1,
                    'cast_speed'        => 1.7,
                    'accuracy'          => 200,
                    'magic_accuracy'    => 100,
                    'block_ignoring'    => 0,
                    'critical_chance'   => 10,
                    'damage_multiplier' => 100,
                    'vampirism'         => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CRITICAL_MULTIPLIER,
            ],
            [
                // critical_multiplier некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => [],
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CRITICAL_MULTIPLIER,
            ],
            [
                // critical_multiplier меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => OffenseInterface::MIN_CRITICAL_MULTIPLIER - 1,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CRITICAL_MULTIPLIER_VALUE . OffenseInterface::MIN_CRITICAL_MULTIPLIER . '-' . OffenseInterface::MAX_CRITICAL_MULTIPLIER,
            ],
            [
                // critical_multiplier больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => OffenseInterface::MAX_CRITICAL_MULTIPLIER + 1,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_CRITICAL_MULTIPLIER_VALUE . OffenseInterface::MIN_CRITICAL_MULTIPLIER . '-' . OffenseInterface::MAX_CRITICAL_MULTIPLIER,
            ],

            // damage_multiplier
            [
                // Отсутствует damage_multiplier
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_DAMAGE_MULTIPLIER,
            ],
            [
                // damage_multiplier некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => null,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_DAMAGE_MULTIPLIER,
            ],
            [
                // damage_multiplier меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => OffenseInterface::MIN_DAMAGE_MULTIPLIER - 1,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_DAMAGE_MULTIPLIER_VALUE . OffenseInterface::MIN_DAMAGE_MULTIPLIER . '-' . OffenseInterface::MAX_DAMAGE_MULTIPLIER,
            ],
            [
                // damage_multiplier больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 10,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => OffenseInterface::MAX_DAMAGE_MULTIPLIER + 1,
                    'vampirism'           => 0,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_DAMAGE_MULTIPLIER_VALUE . OffenseInterface::MIN_DAMAGE_MULTIPLIER . '-' . OffenseInterface::MAX_DAMAGE_MULTIPLIER,
            ],

            // vampirism
            [
                // Отсутствует vampirism
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_VAMPIRISM,
            ],
            [
                // vampirism некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => '0',
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_VAMPIRISM,
            ],
            [
                // vampirism меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => OffenseInterface::MIN_VAMPIRISM - 1,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_VAMPIRISM_VALUE . OffenseInterface::MIN_VAMPIRISM . '-' . OffenseInterface::MAX_VAMPIRISM,
            ],
            [
                // vampirism больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => OffenseInterface::MAX_VAMPIRISM + 1,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_VAMPIRISM_VALUE . OffenseInterface::MIN_VAMPIRISM . '-' . OffenseInterface::MAX_VAMPIRISM,
            ],

            // weapon_type
            [
                // Отсутствует weapon_type
                [
                    'damage_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_WEAPON_TYPE,
            ],
            [
                // weapon_type некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => null,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'vampirism'           => '0',
                    'damage_multiplier'   => 100,
                    'magic_vampirism'     => 0,
                ],
                OffenseException::INCORRECT_WEAPON_TYPE,
            ],


            // magic_vampirism
            [
                // Отсутствует magic_vampirism
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                ],
                OffenseException::INCORRECT_MAGIC_VAMPIRISM,
            ],
            [
                // magic_vampirism некорректного типа
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => '0',
                ],
                OffenseException::INCORRECT_MAGIC_VAMPIRISM,
            ],
            [
                // magic_vampirism меньше минимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => OffenseInterface::MIN_VAMPIRISM - 1,
                ],
                OffenseException::INCORRECT_MAGIC_VAMPIRISM_VALUE . OffenseInterface::MIN_VAMPIRISM . '-' . OffenseInterface::MAX_VAMPIRISM,
            ],
            [
                // magic_vampirism больше максимального значения
                [
                    'damage_type'         => 1,
                    'weapon_type'         => 1,
                    'physical_damage'     => 10,
                    'fire_damage'         => 0,
                    'water_damage'        => 0,
                    'air_damage'          => 0,
                    'earth_damage'        => 0,
                    'life_damage'         => 0,
                    'death_damage'        => 0,
                    'attack_speed'        => 1,
                    'cast_speed'          => 1.7,
                    'accuracy'            => 200,
                    'magic_accuracy'      => 100,
                    'block_ignoring'      => 0,
                    'critical_chance'     => 5,
                    'critical_multiplier' => 200,
                    'damage_multiplier'   => 100,
                    'vampirism'           => 0,
                    'magic_vampirism'     => OffenseInterface::MAX_VAMPIRISM + 1,
                ],
                OffenseException::INCORRECT_MAGIC_VAMPIRISM_VALUE . OffenseInterface::MIN_VAMPIRISM . '-' . OffenseInterface::MAX_VAMPIRISM,
            ],

        ];
    }

    /**
     * @return OffenseFactory
     */
    private function getFactory(): OffenseFactory
    {
        return new OffenseFactory();
    }

    /**
     * @return DefenseInterface
     * @throws Exception
     */
    private function getDefense(): DefenseInterface
    {
        return new Defense(
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            10,
            10,
            10,
            5,
            0,
            75,
            75,
            75,
            75,
            75,
            75,
            75,
            0,
            0
        );
    }
}
