# Created by WalkWeb, 2025

image: walkweb/php-8.4-mysql

cache:
  paths:
    - vendor/

stages:
  - build
  - static analysis
  - tests

composer install:
  stage: build
  script:
    - composer install

code style:
  stage: static analysis
  script:
    - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer check src

phpstan:
  stage: static analysis
  script:
    - php -d memory_limit=512M vendor/bin/phpstan analyse src

rector:
  stage: static analysis
  script:
    - php vendor/bin/rector -n

unit tests:
  stage: tests
  script:
    - php vendor/bin/phpunit
