<?php

declare(strict_types=1);

namespace Tests\Battle\Unit;

use Battle\Unit\Classes\UnitClassFactory;
use Battle\Unit\Race\RaceFactory;
use Battle\Unit\UnitException;
use Battle\Unit\UnitFactory;
use Battle\Unit\UnitInterface;
use Exception;
use Tests\AbstractUnitTest;

class UnitFactoryTest extends AbstractUnitTest
{
    /**
     * Тест на успешное создание юнита через UnitFactory
     *
     * @dataProvider successDataProvider
     * @param array $data
     * @throws Exception
     */
    public function testUnitFactorySuccess(array $data): void
    {
        $unit = UnitFactory::create($data);
        $class = array_key_exists('class', $data) && is_int($data['class']) ? UnitClassFactory::create($data['class']) : null;
        $race = RaceFactory::create($data['race']);

        self::assertEquals($data['name'], $unit->getName());
        self::assertEquals($data['level'], $unit->getLevel());
        self::assertEquals($data['avatar'], $unit->getAvatar());
        self::assertEquals($data['damage'], $unit->getDamage());
        self::assertEquals($data['attack_speed'], $unit->getAttackSpeed());
        self::assertEquals($data['accuracy'], $unit->getAccuracy());
        self::assertEquals($data['defence'], $unit->getDefence());
        self::assertEquals($data['life'], $unit->getTotalLife());
        self::assertEquals($data['life'], $unit->getLife());
        self::assertEquals($data['melee'], $unit->isMelee());
        self::assertEquals($data['command'], $unit->getCommand());
        self::assertEquals($class, $unit->getClass());
        self::assertEquals($race, $unit->getRace());
    }

    /**
     * Тесты на различные варианты невалидных данных для создания юнита
     *
     * @dataProvider failDataProvider
     * @param array $data
     * @param string $error
     * @throws Exception
     */
    public function testUnitFactoryFail(array $data, string $error): void
    {
        $this->expectException(Exception::class);
        $this->expectErrorMessage($error);
        UnitFactory::create($data);
    }

    /**
     * Тест на замену спецсимволов в имени юнита
     *
     * @throws Exception
     */
    public function testUnitFactoryHtmlspecialchars(): void
    {
        $data = [
            'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
            'name'         => '<b>Skeleton</b>',
            'level'        => 1,
            'avatar'       => '/images/avas/monsters/003.png',
            'damage'       => 15,
            'attack_speed' => 1.2,
            'accuracy'     => 200,
            'defence'      => 100,
            'block'        => 0,
            'block_ignore' => 0,
            'life'         => 80,
            'total_life'   => 80,
            'melee'        => true,
            'class'        => 1,
            'race'         => 8,
            'command'      => 1,
        ];

        $unit = UnitFactory::create($data);

        self::assertEquals(htmlspecialchars($data['name']), $unit->getName());
    }

    /**
     * @return array
     */
    public function successDataProvider(): array
    {
        return [
            [
                // attack_speed float
                [
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
            ],
            [
                // attack_speed int - такой вариант также доступен
                [
                    'id'           => '5aa0d764-e92d-4137-beed-f7f590b08165',
                    'name'         => 'Skeleton',
                    'level'        => 5,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 8,
                    'command'      => 1,
                ],
            ],
            [
                // отсутствует класс
                [
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'race'         => 1,
                    'command'      => 1,
                ],
            ],
            [
                // класс = null
                [
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => null,
                    'race'         => 1,
                    'command'      => 2,
                ],
            ],
        ];
    }

    /**
     * @return array
     */
    public function failDataProvider(): array
    {
        return [
            [
                [
                    // отсутствует id
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_ID,
            ],
            [
                [
                    // id некорректного типа
                    'id'           => 123123,
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_ID,
            ],
            [
                [
                    // id меньше минимальной длины (0)
                    'id'           => '',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_ID_VALUE . UnitInterface::MIN_ID_LENGTH . '-' . UnitInterface::MAX_ID_LENGTH,
            ],
            [
                [
                    // id больше минимальной длины (4)
                    'id'           => 'llllllllllllllllllllllllllllllllllllllll',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_ID_VALUE . UnitInterface::MIN_ID_LENGTH . '-' . UnitInterface::MAX_ID_LENGTH,
            ],
            [
                [
                    // отсутствует name
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_NAME,
            ],
            [
                [
                    // некорректный name
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 123,
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_NAME,
            ],
            [
                [
                    // name length < UnitInterface::MIN_NAME_LENGTH
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => '',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_NAME_VALUE . UnitInterface::MIN_NAME_LENGTH . '-' . UnitInterface::MAX_NAME_LENGTH,
            ],
            [
                [
                    // name length > UnitInterface::MAX_NAME_LENGTH
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'lllllllllllllllllllll',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_NAME_VALUE . UnitInterface::MIN_NAME_LENGTH . '-' . UnitInterface::MAX_NAME_LENGTH,
            ],
            [
                [
                    // отсутствует avatar
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_AVATAR,
            ],
            [
                [
                    // некорректный avatar
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => ['ava' => '/images/avas/monsters/003.png'],
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_AVATAR,
            ],
            [
                [
                    // отсутствует damage
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_DAMAGE,
            ],
            [
                [
                    // некорректный damage
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15.3,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_DAMAGE,
            ],
            [
                [
                    // damage < UnitInterface::MIN_DAMAGE
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => UnitInterface::MIN_DAMAGE - 1,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_DAMAGE_VALUE . UnitInterface::MIN_DAMAGE . '-' . UnitInterface::MAX_DAMAGE,
            ],
            [
                [
                    // damage > UnitInterface::MAX_DAMAGE
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => UnitInterface::MAX_DAMAGE + 1,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_DAMAGE_VALUE . UnitInterface::MIN_DAMAGE . '-' . UnitInterface::MAX_DAMAGE,
            ],
            [
                [
                    // отсутствует attack_speed
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_ATTACK_SPEED,
            ],
            [
                [
                    // некорректный attack_speed
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => '1',
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_ATTACK_SPEED,
            ],
            [
                [
                    // attack_speed < UnitInterface::MIN_ATTACK_SPEED
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => UnitInterface::MIN_ATTACK_SPEED - 0.1,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_ATTACK_SPEED_VALUE . UnitInterface::MIN_ATTACK_SPEED . '-' . UnitInterface::MAX_ATTACK_SPEED,
            ],
            [
                [
                    // attack_speed > UnitInterface::MAX_ATTACK_SPEED
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' =>  UnitInterface::MAX_ATTACK_SPEED + 0.1,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_ATTACK_SPEED_VALUE . UnitInterface::MIN_ATTACK_SPEED . '-' . UnitInterface::MAX_ATTACK_SPEED,
            ],
            [
                [
                    // отсутствует life
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_LIFE,
            ],
            [
                [
                    // некорректный life
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80.0,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_LIFE,
            ],
            [
                [
                    // life < UnitInterface::MIN_LIFE
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => UnitInterface::MIN_LIFE - 1,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_LIFE_VALUE . UnitInterface::MIN_LIFE . '-' . UnitInterface::MAX_LIFE,
            ],
            [
                [
                    // life > UnitInterface::MAX_LIFE
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => UnitInterface::MAX_LIFE + 1,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_LIFE_VALUE . UnitInterface::MIN_LIFE . '-' . UnitInterface::MAX_LIFE,
            ],
            [
                [
                    // отсутствует total life
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_TOTAL_LIFE,
            ],
            [
                [
                    // некорректный total life
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80.0,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_TOTAL_LIFE,
            ],
            [
                [
                    // total life < UnitInterface::MIN_TOTAL_LIFE
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 0,
                    'total_life'   => UnitInterface::MIN_TOTAL_LIFE - 1,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_TOTAL_LIFE_VALUE . UnitInterface::MIN_TOTAL_LIFE . '-' . UnitInterface::MAX_TOTAL_LIFE,
            ],
            [
                [
                    // total life > UnitInterface::MAX_TOTAL_LIFE
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 0,
                    'total_life'   => UnitInterface::MAX_TOTAL_LIFE + 1,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_TOTAL_LIFE_VALUE . UnitInterface::MIN_TOTAL_LIFE . '-' . UnitInterface::MAX_TOTAL_LIFE,
            ],
            [
                [
                    // отсутствует melee
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_MELEE,
            ],
            [
                [
                    // некорректный melee
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => 1,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_MELEE,
            ],
            [
                [
                    // некорректный class
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 'warrior',
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_CLASS,
            ],
            [
                [
                    // life большие total life
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 90,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::LIFE_MORE_TOTAL_LIFE,
            ],
            [
                [
                    // level отсутствует
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_LEVEL,
            ],
            [
                [
                    // level некорректного типа
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => '3',
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_LEVEL,
            ],
            [
                [
                    // level < UnitInterface::MIN_LEVEL
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => UnitInterface::MIN_LEVEL - 1,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_LEVEL_VALUE . UnitInterface::MIN_LEVEL . '-' . UnitInterface::MAX_LEVEL,
            ],
            [
                [
                    // level > UnitInterface::MAX_LEVEL
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => UnitInterface::MAX_LEVEL + 1,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_LEVEL_VALUE . UnitInterface::MIN_LEVEL . '-' . UnitInterface::MAX_LEVEL,
            ],
            [
                [
                    // отсутствует race
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_RACE,
            ],
            [
                [
                    // race некорректного типа
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 'human',
                    'command'      => 1,
                ],
                UnitException::INCORRECT_RACE,
            ],
            [
                [
                    // отсутствует command
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                ],
                UnitException::INCORRECT_COMMAND,
            ],
            [
                [
                    // command некорректного типа
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 'left',
                ],
                UnitException::INCORRECT_COMMAND,
            ],
            [
                [
                    // command != 1 && != 2
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 3,
                ],
                UnitException::INCORRECT_COMMAND,
            ],
            [
                // Отсутствует block
                [
                    'id'           => 'f7e84eab-e4f6-469f-b0e3-f5f965f9fbce',
                    'name'         => 'unit_1',
                    'level'        => 1,
                    'avatar'       => '/images/avas/humans/human001.jpg',
                    'damage'       => 20,
                    'attack_speed' => 1.00,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'life'         => 100,
                    'total_life'   => 100,
                    'block_ignore' => 0,
                    'melee'        => true,
                    'command'      => 1,
                    'class'        => 1,
                    'race'         => 1,
                ],
                UnitException::INCORRECT_BLOCK,
            ],
            [
                // block некорректного типа
                [
                    'id'           => 'f7e84eab-e4f6-469f-b0e3-f5f965f9fbce',
                    'name'         => 'unit_1',
                    'level'        => 1,
                    'avatar'       => '/images/avas/humans/human001.jpg',
                    'damage'       => 20,
                    'attack_speed' => 1.00,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => '50',
                    'block_ignore' => 0,
                    'life'         => 100,
                    'total_life'   => 100,
                    'melee'        => true,
                    'command'      => 1,
                    'class'        => 1,
                    'race'         => 1,
                ],
                UnitException::INCORRECT_BLOCK,
            ],
            [
                // block меньше минимального значения
                [
                    'id'           => 'f7e84eab-e4f6-469f-b0e3-f5f965f9fbce',
                    'name'         => 'unit_1',
                    'level'        => 1,
                    'avatar'       => '/images/avas/humans/human001.jpg',
                    'damage'       => 20,
                    'attack_speed' => 1.00,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => UnitInterface::MIN_BLOCK - 1,
                    'block_ignore' => 0,
                    'life'         => 100,
                    'total_life'   => 100,
                    'melee'        => true,
                    'command'      => 1,
                    'class'        => 1,
                    'race'         => 1,
                ],
                UnitException::INCORRECT_BLOCK_VALUE . UnitInterface::MIN_BLOCK . '-' . UnitInterface::MAX_BLOCK,
            ],
            [
                // block больше максимального значения
                [
                    'id'           => 'f7e84eab-e4f6-469f-b0e3-f5f965f9fbce',
                    'name'         => 'unit_1',
                    'level'        => 1,
                    'avatar'       => '/images/avas/humans/human001.jpg',
                    'damage'       => 20,
                    'attack_speed' => 1.00,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => UnitInterface::MAX_BLOCK + 1,
                    'block_ignore' => 0,
                    'life'         => 100,
                    'total_life'   => 100,
                    'melee'        => true,
                    'command'      => 1,
                    'class'        => 1,
                    'race'         => 1,
                ],
                UnitException::INCORRECT_BLOCK_VALUE . UnitInterface::MIN_BLOCK . '-' . UnitInterface::MAX_BLOCK,
            ],
            [
                // Отсутствует block_ignore
                [
                    'id'           => 'f7e84eab-e4f6-469f-b0e3-f5f965f9fbce',
                    'name'         => 'unit_1',
                    'level'        => 1,
                    'avatar'       => '/images/avas/humans/human001.jpg',
                    'damage'       => 20,
                    'attack_speed' => 1.00,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'life'         => 100,
                    'total_life'   => 100,
                    'melee'        => true,
                    'command'      => 1,
                    'class'        => 1,
                    'race'         => 1,
                ],
                UnitException::INCORRECT_BLOCK_IGNORE,
            ],
            [
                // block_ignore некорректного типа
                [
                    'id'           => 'f7e84eab-e4f6-469f-b0e3-f5f965f9fbce',
                    'name'         => 'unit_1',
                    'level'        => 1,
                    'avatar'       => '/images/avas/humans/human001.jpg',
                    'damage'       => 20,
                    'attack_speed' => 1.00,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => '50',
                    'life'         => 100,
                    'total_life'   => 100,
                    'melee'        => true,
                    'command'      => 1,
                    'class'        => 1,
                    'race'         => 1,
                ],
                UnitException::INCORRECT_BLOCK_IGNORE,
            ],
            [
                // block_ignore меньше минимального значения
                [
                    'id'           => 'f7e84eab-e4f6-469f-b0e3-f5f965f9fbce',
                    'name'         => 'unit_1',
                    'level'        => 1,
                    'avatar'       => '/images/avas/humans/human001.jpg',
                    'damage'       => 20,
                    'attack_speed' => 1.00,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => UnitInterface::MIN_BLOCK_IGNORE - 1,
                    'life'         => 100,
                    'total_life'   => 100,
                    'melee'        => true,
                    'command'      => 1,
                    'class'        => 1,
                    'race'         => 1,
                ],
                UnitException::INCORRECT_BLOCK_IGNORE_VALUE. UnitInterface::MIN_BLOCK_IGNORE . '-' . UnitInterface::MAX_BLOCK_IGNORE,
            ],
            [
                // block_ignore больше максимального значения
                [
                    'id'           => 'f7e84eab-e4f6-469f-b0e3-f5f965f9fbce',
                    'name'         => 'unit_1',
                    'level'        => 1,
                    'avatar'       => '/images/avas/humans/human001.jpg',
                    'damage'       => 20,
                    'attack_speed' => 1.00,
                    'accuracy'     => 200,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => UnitInterface::MAX_BLOCK_IGNORE + 1,
                    'life'         => 100,
                    'total_life'   => 100,
                    'melee'        => true,
                    'command'      => 1,
                    'class'        => 1,
                    'race'         => 1,
                ],
                UnitException::INCORRECT_BLOCK_IGNORE_VALUE. UnitInterface::MIN_BLOCK_IGNORE . '-' . UnitInterface::MAX_BLOCK_IGNORE,
            ],
            [
                // Отсутствует accuracy
                [
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_ACCURACY
            ],
            [
                // accuracy некорректного типа
                [
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => '200',
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_ACCURACY
            ],
            [
                // accuracy меньше минимальной длины
                [
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => UnitInterface::MIN_ACCURACY - 1,
                    'defence'      => 100,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_ACCURACY_VALUE . UnitInterface::MIN_ACCURACY,
            ],
            [
                // Отсутствует defence
                [
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_DEFENCE
            ],
            [
                // defence некорректного типа
                [
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => [100],
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_DEFENCE
            ],
            [
                // defence меньше минимальной длины
                [
                    'id'           => '5a9e559a-954d-4b7c-98fe-4e9609523e6e',
                    'name'         => 'Skeleton',
                    'level'        => 3,
                    'avatar'       => '/images/avas/monsters/003.png',
                    'damage'       => 15,
                    'attack_speed' => 1.2,
                    'accuracy'     => 200,
                    'defence'      => UnitInterface::MIN_DEFENCE - 1,
                    'block'        => 0,
                    'block_ignore' => 0,
                    'life'         => 80,
                    'total_life'   => 80,
                    'melee'        => true,
                    'class'        => 1,
                    'race'         => 1,
                    'command'      => 1,
                ],
                UnitException::INCORRECT_DEFENCE_VALUE . UnitInterface::MIN_DEFENCE,
            ],
        ];
    }
}
