<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Battle\BattleFactory;

$data = [
    [
        'id'                           => '60f3c032-46a6-454d-ae3a-d066f150f6ef',
        'name'                         => 'Titan',
        'level'                        => 3,
        'avatar'                       => '/images/avas/orcs/orc001.jpg',
        'life'                         => 185,
        'total_life'                   => 185,
        'mana'                         => 38,
        'total_mana'                   => 38,
        'melee'                        => true,
        'command'                      => 1,
        'class'                        => 5,
        'race'                         => 3,
        'add_concentration_multiplier' => 0,
        'cunning_multiplier'           => 0,
        'add_rage_multiplier'          => 0,
        'offense'                      => [
            'damage_type'         => 1,
            'weapon_type'         => 2,
            'physical_damage'     => 47,
            'fire_damage'         => 0,
            'water_damage'        => 0,
            'air_damage'          => 0,
            'earth_damage'        => 0,
            'life_damage'         => 0,
            'death_damage'        => 0,
            'attack_speed'        => 1.2,
            'cast_speed'          => 0,
            'accuracy'            => 176,
            'magic_accuracy'      => 12,
            'block_ignoring'      => 0,
            'critical_chance'     => 5,
            'critical_multiplier' => 200,
            'damage_multiplier'   => 100,
            'vampirism'           => 0,
            'magic_vampirism'     => 0,
        ],
        'defense'                      => [
            'physical_resist'     => 30,
            'fire_resist'         => 25,
            'water_resist'        => 0,
            'air_resist'          => 0,
            'earth_resist'        => 0,
            'life_resist'         => 0,
            'death_resist'        => 0,
            'defense'             => 134,
            'magic_defense'       => 31,
            'block'               => 0,
            'magic_block'         => 0,
            'mental_barrier'      => 0,
            'max_physical_resist' => 75,
            'max_fire_resist'     => 75,
            'max_water_resist'    => 75,
            'max_air_resist'      => 75,
            'max_earth_resist'    => 75,
            'max_life_resist'     => 75,
            'max_death_resist'    => 75,
            'global_resist'       => 0,
            'dodge'               => 0,
        ],
    ],
    [
        'id'                           => 'f7e84eab-e4f6-469f-b0e3-f5f965f9fbce',
        'name'                         => 'Warrior',
        'level'                        => 2,
        'avatar'                       => '/images/avas/humans/human001.jpg',
        'life'                         => 160,
        'total_life'                   => 160,
        'mana'                         => 61,
        'total_mana'                   => 61,
        'melee'                        => true,
        'command'                      => 1,
        'class'                        => 1,
        'race'                         => 1,
        'add_concentration_multiplier' => 20,
        'cunning_multiplier'           => 0,
        'add_rage_multiplier'          => 0,
        'offense'                      => [
            'damage_type'         => 1,
            'weapon_type'         => 1,
            'physical_damage'     => 0,
            'fire_damage'         => 0,
            'water_damage'        => 0,
            'air_damage'          => 0,
            'earth_damage'        => 32,
            'life_damage'         => 0,
            'death_damage'        => 0,
            'attack_speed'        => 1.1,
            'cast_speed'          => 0,
            'accuracy'            => 212,
            'magic_accuracy'      => 14,
            'block_ignoring'      => 0,
            'critical_chance'     => 10,
            'critical_multiplier' => 200,
            'damage_multiplier'   => 100,
            'vampirism'           => 0,
            'magic_vampirism'     => 0,
        ],
        'defense'                      => [
            'physical_resist'     => 20,
            'fire_resist'         => 0,
            'water_resist'        => 5,
            'air_resist'          => 0,
            'earth_resist'        => 0,
            'life_resist'         => 0,
            'death_resist'        => 10,
            'defense'             => 155,
            'magic_defense'       => 63,
            'block'               => 25,
            'magic_block'         => 0,
            'mental_barrier'      => 0,
            'max_physical_resist' => 75,
            'max_fire_resist'     => 75,
            'max_water_resist'    => 75,
            'max_air_resist'      => 75,
            'max_earth_resist'    => 75,
            'max_life_resist'     => 75,
            'max_death_resist'    => 75,
            'global_resist'       => 0,
            'dodge'               => 0,
        ],
    ],
    [
        'id'                           => '2c58854d-e0ad-4d29-86e4-62bbb4b8d3b7',
        'name'                         => 'Alchemist',
        'level'                        => 3,
        'avatar'                       => '/images/avas/dwarfs/dwarf004.jpg',
        'life'                         => 115,
        'total_life'                   => 115,
        'mana'                         => 358,
        'total_mana'                   => 358,
        'melee'                        => false,
        'command'                      => 1,
        'class'                        => 6,
        'race'                         => 4,
        'add_concentration_multiplier' => 0,
        'cunning_multiplier'           => 0,
        'add_rage_multiplier'          => 0,
        'offense'                      => [
            'damage_type'         => 2,
            'weapon_type'         => 7,
            'physical_damage'     => 0,
            'fire_damage'         => 0,
            'water_damage'        => 0,
            'air_damage'          => 21,
            'earth_damage'        => 0,
            'life_damage'         => 0,
            'death_damage'        => 0,
            'attack_speed'        => 0,
            'cast_speed'          => 1.1,
            'accuracy'            => 198,
            'magic_accuracy'      => 213,
            'block_ignoring'      => 0,
            'critical_chance'     => 15,
            'critical_multiplier' => 150,
            'damage_multiplier'   => 100,
            'vampirism'           => 0,
            'magic_vampirism'     => 0,
        ],
        'defense'                      => [
            'physical_resist'     => 0,
            'fire_resist'         => 20,
            'water_resist'        => 20,
            'air_resist'          => 20,
            'earth_resist'        => 20,
            'life_resist'         => 0,
            'death_resist'        => 0,
            'defense'             => 138,
            'magic_defense'       => 193,
            'block'               => 0,
            'magic_block'         => 0,
            'mental_barrier'      => 0,
            'max_physical_resist' => 75,
            'max_fire_resist'     => 75,
            'max_water_resist'    => 75,
            'max_air_resist'      => 75,
            'max_earth_resist'    => 75,
            'max_life_resist'     => 75,
            'max_death_resist'    => 75,
            'global_resist'       => 0,
            'dodge'               => 0,
        ],
    ],
    [
        'id'                           => '942be229-2272-45d5-94ec-4c20be94a344',
        'name'                         => 'Succubus',
        'level'                        => 2,
        'avatar'                       => '/images/avas/demons/demon010.jpg',
        'life'                         => 90,
        'total_life'                   => 90,
        'mana'                         => 114,
        'total_mana'                   => 114,
        'melee'                        => false,
        'command'                      => 1,
        'class'                        => 7,
        'race'                         => 6,
        'add_concentration_multiplier' => 0,
        'cunning_multiplier'           => 0,
        'add_rage_multiplier'          => 0,
        'offense'                      => [
            'damage_type'         => 2,
            'weapon_type'         => 7,
            'physical_damage'     => 0,
            'fire_damage'         => 0,
            'water_damage'        => 0,
            'air_damage'          => 0,
            'earth_damage'        => 0,
            'life_damage'         => 0,
            'death_damage'        => 25,
            'attack_speed'        => 0,
            'cast_speed'          => 1.2,
            'accuracy'            => 241,
            'magic_accuracy'      => 286,
            'block_ignoring'      => 0,
            'critical_chance'     => 20,
            'critical_multiplier' => 250,
            'damage_multiplier'   => 100,
            'vampirism'           => 0,
            'magic_vampirism'     => 0,
        ],
        'defense'                      => [
            'physical_resist'     => 0,
            'fire_resist'         => 40,
            'water_resist'        => 0,
            'air_resist'          => 0,
            'earth_resist'        => 0,
            'life_resist'         => 0,
            'death_resist'        => 30,
            'defense'             => 178,
            'magic_defense'       => 146,
            'block'               => 0,
            'magic_block'         => 0,
            'mental_barrier'      => 100,
            'max_physical_resist' => 75,
            'max_fire_resist'     => 75,
            'max_water_resist'    => 75,
            'max_air_resist'      => 75,
            'max_earth_resist'    => 75,
            'max_life_resist'     => 75,
            'max_death_resist'    => 75,
            'global_resist'       => 0,
            'dodge'               => 0,
        ],
    ],
    [
        'id'                           => 'e53b7edd-a4b5-49c4-81a2-050a1b7ecbea',
        'name'                         => 'Warden',
        'level'                        => 5,
        'avatar'                       => '/images/avas/bosses/011.png',
        'life'                         => 648,
        'total_life'                   => 648,
        'mana'                         => 216,
        'total_mana'                   => 216,
        'melee'                        => true,
        'command'                      => 2,
        'class'                        => 50,
        'race'                         => 9,
        'add_concentration_multiplier' => 0,
        'cunning_multiplier'           => 0,
        'add_rage_multiplier'          => 0,
        'offense'                      => [
            'damage_type'         => 1,
            'weapon_type'         => 17,
            'physical_damage'     => 72,
            'fire_damage'         => 0,
            'water_damage'        => 0,
            'air_damage'          => 0,
            'earth_damage'        => 0,
            'life_damage'         => 0,
            'death_damage'        => 0,
            'attack_speed'        => 1,
            'cast_speed'          => 0,
            'accuracy'            => 252,
            'magic_accuracy'      => 413,
            'block_ignoring'      => 0,
            'critical_chance'     => 10,
            'critical_multiplier' => 200,
            'damage_multiplier'   => 100,
            'vampirism'           => 0,
            'magic_vampirism'     => 0,
        ],
        'defense'                      => [
            'physical_resist'     => 30,
            'fire_resist'         => 50,
            'water_resist'        => 0,
            'air_resist'          => 0,
            'earth_resist'        => 0,
            'life_resist'         => 0,
            'death_resist'        => 20,
            'defense'             => 106,
            'magic_defense'       => 211,
            'block'               => 20,
            'magic_block'         => 0,
            'mental_barrier'      => 0,
            'max_physical_resist' => 75,
            'max_fire_resist'     => 75,
            'max_water_resist'    => 75,
            'max_air_resist'      => 75,
            'max_earth_resist'    => 75,
            'max_life_resist'     => 75,
            'max_death_resist'    => 75,
            'global_resist'       => 0,
            'dodge'               => 0,
        ],
    ],
];

try {
    $battle = BattleFactory::create($data);
    $response = $battle->handle();

    $view = $battle->getContainer()->getViewFactory()->create();
    echo $view->renderHead(); // example layout styles
    echo $view->renderBattle($response);

} catch (Exception $e) {
    die($e->getMessage());
}
