<?php

declare(strict_types=1);

namespace Tests\Battle\Factory;

use Battle\Container\Container;
use Battle\Container\ContainerInterface;
use Battle\Unit\Defense\DefenseFactory;
use Battle\Unit\Offense\OffenseFactory;
use Battle\Unit\UnitInterface;
use Battle\Unit\Unit;
use Exception;

class UnitFactory
{
    private static array $units = [
        // Warrior
        1  => [
            'id'         => 'f7e84eab-e4f6-469f-b0e3-f5f965f9fbce',
            'name'       => 'unit_1',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human001.jpg',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 20,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        2  => [
            'id'         => '1aab367d-37e8-4544-9915-cb3d7779308b',
            'name'       => 'unit_2',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human002.jpg',
            'life'       => 250,
            'total_life' => 250,
            'mana'       => 50,
            'total_mana' => 50,
            'command'    => 1,
            'melee'      => true,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 30,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        3  => [
            'id'         => '72df87f5-b3a7-4574-9526-45a20aa77119',
            'name'       => 'unit_3',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human003.jpg',
            'life'       => 120,
            'total_life' => 120,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 15,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        4  => [
            'id'         => 'c310ce86-7bb2-44b0-b634-ea0d28fb1180',
            'name'       => 'unit_4',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human004.jpg',
            'life'       => 20,
            'total_life' => 20,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 15,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Priest
        5  => [
            'id'         => '46d969c1-463b-42b1-a2e0-2c64a8c34ae1',
            'name'       => 'unit_5',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/003.png',
            'life'       => 80,
            'total_life' => 80,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => false,
            'command'    => 1,
            'class'      => 2,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 2,
                'physical_damage'     => 15,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        6  => [
            'id'         => '1e813812-9a21-4e18-b494-8d552bac0cf4',
            'name'       => 'unit_6',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/003.png',
            'life'       => 50,
            'total_life' => 50,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => false,
            'command'    => 1,
            'class'      => 2,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 12,
                'attack_speed'        => 1.1,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        7  => [
            'id'         => '46d969c1-463b-42b1-a2e0-2c62a8c34ae3',
            'name'       => 'unit_7',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/003.png',
            'life'       => 80,
            'total_life' => 80,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => false,
            'command'    => 1,
            'class'      => 4,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 15,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        8  => [
            'id'         => 'f7e84eab-e4f6-463f-b0e3-f2f965f4fbce',
            'name'       => 'unit_8',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human001.jpg',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 3,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 20,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Слегка раненый юнит
        9  => [
            'id'         => '5e5c15fb-fa29-4bf0-8a0d-f2be9f90ca9d',
            'name'       => 'small_wounded_unit',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/005.png',
            'life'       => 90,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 35,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Мертвый юнит
        10 => [
            'id'         => '92e7b39c-dbfc-4493-b563-50314c524c0c',
            'name'       => 'dead_unit',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/005.png',
            'life'       => 0,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 35,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Сильно раненый юнит
        11 => [
            'id'         => '92e7b39c-dbfc-4493-b563-50314c524c3c',
            'name'       => 'wounded_unit',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/005.png',
            'life'       => 1,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 35,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        12 => [
            'id'         => '1aab367d-37e8-4544-9915-cb3d7779332b',
            'name'       => 'unit_12',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human002.jpg',
            'life'       => 150,
            'total_life' => 150,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 2,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 3000,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        13 => [
            'id'         => '1aab367d-37e8-4544-9915-cb3d7779332b',
            'name'       => 'unit_13',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human002.jpg',
            'life'       => 150,
            'total_life' => 150,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 3000,
                'attack_speed'        => 5, // Не просто большой урон, но и 5 атак за ход
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        14 => [
            'id'         => '1aab367d-37e8-4544-9915-cb3d7779323b',
            'name'       => 'unit_14',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human002.jpg',
            'life'       => 150,
            'total_life' => 150,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 32,
                'attack_speed'        => 0, // нулевая скорость атаки
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Юнит для подсчета дополнительных атак, с.м. тест testUnitCalculateAttackSpeed
        15 => [
            'id'         => '1aab367d-37e8-4544-9915-cb3d77793237',
            'name'       => 'unit_15',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human002.jpg',
            'life'       => 150,
            'total_life' => 150,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 32,
                'attack_speed'        => 1.9999,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Юнит для подсчета дополнительных атак, с.м. тест testUnitCalculateAttackSpeed
        16 => [
            'id'         => '1aab367d-37e8-4544-9915-cb3d77793239',
            'name'       => 'unit_16',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human002.jpg',
            'life'       => 150,
            'total_life' => 150,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 32,
                'attack_speed'        => 1.0001,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        17 => [
            'id'         => '57b11b16-c1fc-463a-a2a0-9dff8a7e2d5c',
            'name'       => 'Zombie',
            'level'      => 2,
            'avatar'     => '/images/avas/monsters/006.png',
            'life'       => 62,
            'total_life' => 62,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'class'      => null,
            'race'       => 8,
            'command'    => 2,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 23,
                'attack_speed'        => 0.7,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Аналог юнита из SummonImpAbility
        18 => [
            'id'         => '57b11b16-c1fc-463a-a2a0-9dff8a7e2333',
            'name'       => 'Imp',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/004.png',
            'life'       => 30,
            'total_life' => 30,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'class'      => null,
            'race'       => 9,
            'command'    => 2,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 10,
                'attack_speed'        => 1,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Аналог юнита из SummonSkeletonMageAbility
        19 => [
            'id'         => '57b11b16-c1fc-463a-a2a0-9dff8a7e2326',
            'name'       => 'Skeleton Mage',
            'level'      => 2,
            'avatar'     => '/images/avas/monsters/008.png',
            'life'       => 42,
            'total_life' => 42,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => false,
            'class'      => null,
            'race'       => 8,
            'command'    => 2,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 13,
                'attack_speed'        => 1.2,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Аналог юнита из SummonSkeletonAbility
        20 => [
            'id'         => '57b11b16-c1fc-463a-a2a0-9dff8a7e2541',
            'name'       => 'Skeleton',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/003.png',
            'life'       => 38,
            'total_life' => 38,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'class'      => null,
            'race'       => 8,
            'command'    => 2,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 16,
                'attack_speed'        => 1,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Орк с классом Титан
        21 => [
            'id'         => '60f3c032-46a6-454d-ae3a-d066f150f6ef',
            'name'       => 'Titan',
            'level'      => 3,
            'avatar'     => '/images/avas/orcs/orc001.jpg',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 5,
            'race'       => 3,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 27,
                'attack_speed'        => 0.8,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Гном с классом Алхимик
        22 => [
            'id'         => '2c58854d-e0ad-4d29-86e4-62bbb4b8d3b7',
            'name'       => 'Alchemist',
            'level'      => 3,
            'avatar'     => '/images/avas/dwarfs/dwarf004.jpg',
            'life'       => 75,
            'total_life' => 75,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => false,
            'command'    => 1,
            'class'      => 6,
            'race'       => 4,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 13,
                'attack_speed'        => 1.1,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Демон с классом Суккуб
        23 => [
            'id'         => '942be229-2272-45d5-94ec-4c20be94a344',
            'name'       => 'Succubus',
            'level'      => 2,
            'avatar'     => '/images/avas/demons/demon010.jpg',
            'life'       => 69,
            'total_life' => 69,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => false,
            'command'    => 1,
            'class'      => 7,
            'race'       => 6,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 11,
                'attack_speed'        => 1.2,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Мертвый юнит с небольшим количеством здоровья
        24 => [
            'id'         => 'ffd35911-4bec-494a-afe8-f6492d81847f',
            'name'       => 'dead_unit_low_life',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/005.png',
            'life'       => 0,
            'total_life' => 10,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 35,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Человек с классом Priest
        25 => [
            'id'         => 'e09b2794-5075-4186-a1ed-31e40cd3fda2',
            'name'       => 'Priest',
            'level'      => 4,
            'avatar'     => '/images/avas/humans/human004.jpg',
            'life'       => 140,
            'total_life' => 140,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => false,
            'command'    => 1,
            'class'      => 2,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 13,
                'attack_speed'        => 1.20,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Элементаль огня
        26 => [
            'id'         => '0b23abe7-00ee-4ff4-a7c7-5d81f4abd201',
            'name'       => 'Fire Elemental',
            'level'      => 3,
            'avatar'     => '/images/avas/summon/fire-elemental.png',
            'life'       => 62,
            'total_life' => 62,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => null,
            'race'       => 10,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 17,
                'attack_speed'        => 1.1,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Босс Warden
        27 => [
            'id'         => 'e53b7edd-a4b5-49c4-81a2-050a1b7ecbea',
            'name'       => 'Warden',
            'level'      => 5,
            'avatar'     => '/images/avas/bosses/011.png',
            'life'       => 300,
            'total_life' => 300,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 2,
            'class'      => 50,
            'race'       => 9,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 40,
                'attack_speed'        => 1,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Юнит со 100% шансом блока
        28 => [
            'id'         => '818b6a3f-a994-412e-9210-88dbd6962d9d',
            'name'       => '100_block',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human001.jpg',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 20,
                'attack_speed'        => 1,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 100,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Юнит с игнорированием блока = 100
        29 => [
            'id'         => '43db979a-827e-4168-a729-11e51245952d',
            'name'       => '100_block_ignore',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human001.jpg',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 20,
                'attack_speed'        => 1,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 100,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Юнит с очень высокими показателями accuracy и defense
        30 => [
            'id'         => '1e7a83ff-bce6-4a76-bb35-fea7130dfc28',
            'name'       => 'nimble_unit',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human001.jpg',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 20,
                'attack_speed'        => 1,
                'accuracy'            => 100000,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100000,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Юнит с 29% здоровья, для проверки активации RageAbility
        31 => [
            'id'         => '92e7b39c-dbfc-4493-b563-50314c524c3c',
            'name'       => 'wounded_orc',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/005.png',
            'life'       => 29,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 3,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 35,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // Юнит со 100% ментальным барьером и 100 маны
        32 => [
            'id'         => '5ab57a34-232f-4d94-a2c9-bb19f41b4e25',
            'name'       => 'unit_5',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/003.png',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 100,
            'total_mana' => 100,
            'melee'      => false,
            'command'    => 1,
            'class'      => 2,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 15,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 100,
            ],
        ],
        // Юнит со 100% ментальным барьером и 0 маны
        33 => [
            'id'         => '87fc2e80-360c-46df-956d-6a8811b43805',
            'name'       => 'unit_5',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/003.png',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 0,
            'total_mana' => 100,
            'melee'      => false,
            'command'    => 1,
            'class'      => 2,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 15,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 100,
            ],
        ],
        // Юнит со 100% ментальным барьером и 10 маны
        34 => [
            'id'         => 'b7eac98a-5628-43f9-b0c8-8389ca5e4667',
            'name'       => 'unit_5',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/003.png',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 10,
            'total_mana' => 100,
            'melee'      => false,
            'command'    => 1,
            'class'      => 2,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 15,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 100,
            ],
        ],
        // Юнит со 50% ментальным барьером и 100 маны
        35 => [
            'id'         => 'e9d27aac-eb38-4077-ad51-f4b6e335af01',
            'name'       => 'unit_5',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/003.png',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 100,
            'total_mana' => 100,
            'melee'      => false,
            'command'    => 1,
            'class'      => 2,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 15,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 50,
            ],
        ],
        // Юнит со 75% ментальным барьером и 5 маны
        36 => [
            'id'         => 'e9d27aac-eb38-4077-ad51-f4b6e335af01',
            'name'       => 'unit_5',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/003.png',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 5,
            'total_mana' => 100,
            'melee'      => false,
            'command'    => 1,
            'class'      => 2,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 15,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 80,
            ],
        ],
        // юнит с magic_accuracy и magic_defense = 100000 и типом атаки заклинание
        37 => [
            'id'         => 'bcab3c38-6d9c-451a-9610-25c055b8177c',
            'name'       => 'unit_5',
            'level'      => 1,
            'avatar'     => '/images/avas/monsters/003.png',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 100,
            'total_mana' => 100,
            'melee'      => false,
            'command'    => 1,
            'class'      => 2,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 2,
                'physical_damage'     => 15,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100000,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 100000,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // юнит со 100% магическим блоком
        38 => [
            'id'         => 'c04fefac-d06d-45b5-9f47-52679b7b5c4a',
            'name'       => 'unit_1',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human001.jpg',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 20,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 100,
                'mental_barrier'  => 0,
            ],
        ],
        // юнит с 80% сопротивлением физическому урону
        39 => [
            'id'         => 'a7fbefd4-a90e-4077-88d5-11ea4d51bbc9',
            'name'       => 'unit_1',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human001.jpg',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 20,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 5,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 80,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 100,
                'mental_barrier'  => 0,
            ],
        ],
        // юнит с 50% шансом критического удара - в тестовом режиме округляется в 100%
        40 => [
            'id'         => 'ec3e550a-7344-445f-8443-ff75e5e018de',
            'name'       => 'unit_1',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human001.jpg',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 20,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 50,
                'critical_multiplier' => 200,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],
        // юнит с 49% шансом критического удара - в тестовом режиме округляется в 0%
        41 => [
            'id'         => 'f46beaa6-c266-45ed-8d4e-6a8bf3e832f0',
            'name'       => 'unit_1',
            'level'      => 1,
            'avatar'     => '/images/avas/humans/human001.jpg',
            'life'       => 100,
            'total_life' => 100,
            'mana'       => 50,
            'total_mana' => 50,
            'melee'      => true,
            'command'    => 1,
            'class'      => 1,
            'race'       => 1,
            'offense'    => [
                'type_damage'         => 1,
                'physical_damage'     => 20,
                'attack_speed'        => 1.00,
                'accuracy'            => 200,
                'magic_accuracy'      => 100,
                'block_ignore'        => 0,
                'critical_chance'     => 49,
                'critical_multiplier' => 300,
            ],
            'defense'    => [
                'physical_resist' => 0,
                'defense'         => 100,
                'magic_defense'   => 50,
                'block'           => 0,
                'magic_block'     => 0,
                'mental_barrier'  => 0,
            ],
        ],

    ];

    /**
     * @param int $template
     * @param ContainerInterface|null $container
     * @return UnitInterface
     * @throws UnitFactoryException
     * @throws Exception
     */
    public static function createByTemplate(int $template, ?ContainerInterface $container = null): UnitInterface
    {
        if (empty(self::$units[$template])) {
            throw new UnitFactoryException(UnitFactoryException::NO_TEMPLATE);
        }

        $data = self::$units[$template];
        $container = $container ?? new Container(true);
        $class = isset($data['class']) ? $container->getUnitClassFactory()->create(
            $container->getClassDataProvider()->get(self::$units[$template]['class'])
        ) : null;

        return new Unit(
            $data['id'],
            $data['name'],
            $data['level'],
            $data['avatar'],
            $data['life'],
            $data['total_life'],
            $data['mana'],
            $data['total_mana'],
            $data['melee'],
            $data['command'],
            OffenseFactory::create($data['offense']),
            DefenseFactory::create($data['defense']),
            $container->getRaceFactory()->create($container->getRaceDataProvider()->get($data['race'])),
            $container,
            $class
        );
    }

    /**
     * @param int $template
     * @return array
     * @throws UnitFactoryException
     */
    public static function getData(int $template): array
    {
        if (empty(self::$units[$template])) {
            throw new UnitFactoryException(UnitFactoryException::NO_TEMPLATE);
        }

        return self::$units[$template];
    }
}
